name: Daily Diaries
run-name: ${{ github.actor }} diary auto push job 

on:
workflow_dispatch:
schedule:
  #æ—¥æœ¬æ™‚é–“23:45
  - cron: '45 14 * * *'

 permissions:
  contents: read
  issues: write 

jobs:
  check_local_and_push:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }}"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."

